name: "Vercel CI"
on: push
jobs:
  vercel:
    runs-on: ubuntu-latest
    name: "Deploy front-end"

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16.13.2"
          registry-url: https://registry.npmjs.org/
          scope: ${{secrets.VERCEL_ORG_ID}}

      - name: "deploy-app"
        run: |
          prodRun=""
          if [[ ${GITHUB_REF} == "refs/heads/main" ]]; then
            prodRun="--prod"
          fi

          npx vercel --token ${VERCEL_SECRET_TOKEN} $prodRun
        env:
          VERCEL_SECRET_TOKEN: ${{secrets.VERCEL_SECRET_TOKEN}}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          NEXT_PUBLIC_UNSPLASH_ACCESS_KEY: ${{secrets.NEXT_PUBLIC_UNSPLASH_ACCESS_KEY}}
          NEXT_PUBLIC_UNSPLASH_SECRET_KEY: ${{secrets.NEXT_PUBLIC_UNSPLASH_SECRET_KEY}}
          NEXT_PUBLIC_EMOJIAPI_ACCESS_KEY: ${{secrets.NEXT_PUBLIC_EMOJIAPI_ACCESS_KEY}}
